import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Canvas from "@/components/layout/Canvas";
import {subscribe} from "@/logic/redis/pubsub";
import {redisClientSub} from "@/provider/redis";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

    subscribe();

    redisClientSub.on('chat', (channel, message) => {
        console.log(message)
    })
    
  return (
    <html lang="en">
      <body>
        <Canvas>{children}</Canvas>
      </body>
    </html>
  );
}
